# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'sideMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sideMenu
  pod 'SWRevealViewController', '~> 2.3'
end
